#!/usr/bin/env bash
#
# Stage the add-on's payload from the single copies in this repo.
#
# Two things have to be produced before `docker build`:
#
#   app/www/ui/             the control panel - index.html, style.css, app.js
#   app/www/sim/            the engine, the wall and the pattern model, which
#                           the add-on's pages load directly (three .js files -
#                           the sandbox's own page is not part of the add-on)
#   app/www/cards/          the same, plus the Lovelace cards - the add-on's
#                           page instantiates the EDITOR CARD itself rather
#                           than reimplementing it
#   app/www/…-card.js       the Lovelace bundle, installed into /config/www at
#                           start so the cards are at /local/
#
# Docker cannot reach outside its build context, so these are COPIES - and
# copies drift. This script is what stops them: run it after changing a mode or
# a card, and never edit anything under app/www by hand.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

# ui/ is the one SOURCE directory staged here rather than a copy of something
# else: it exists only for the add-on. It is staged anyway because Docker copies
# app/ and nothing else.
SIM="../tools/clockclock24-sim"
OUT="app/www/clockclock24-card.js"
PARTS=("$SIM/engine.js" "$SIM/wall.js" "$SIM/pattern.js" "cards/card.js" "cards/editor-card.js")

for f in "${PARTS[@]}"; do
  [ -f "$f" ] || { echo "missing: $f" >&2; exit 1; }
done

rm -rf app/www
mkdir -p app/www/sim app/www/cards app/www/ui

cp ui/index.html ui/display.html ui/style.css ui/app.js ui/display.js app/www/ui/
# The three engine files only. The sandbox's own index.html is NOT staged: the
# add-on's pages load engine/wall/pattern directly and never open that page, and
# it now loads the cards by relative path from the repo root - a path that does
# not exist inside app/, so shipping it would ship a broken page.
cp "$SIM"/engine.js "$SIM"/wall.js "$SIM"/pattern.js app/www/sim/
cp cards/card.js cards/editor-card.js app/www/cards/

# The Lovelace bundle is the same files CONCATENATED, not copied: there is
# exactly one implementation of a choreography in this repo. Change a mode in
# tools/clockclock24-sim and it changes in the firmware port, the project site,
# this add-on and the card together. No npm, no bundler - the sandbox files are
# plain classic scripts that hang everything off window.CC, which is all a
# Lovelace resource needs.
{
  echo "// clockclock24-card - GENERATED by homeassistant/stage.sh"
  echo "// Do not edit. Edit cards/*.js, or the sandbox in tools/clockclock24-sim/, and rebuild."
  echo "// Built from: ${PARTS[*]}"
  echo
  for f in "${PARTS[@]}"; do
    echo "// ─── $(basename "$f") ───────────────────────────────────────────────"
    cat "$f"
    echo
  done
} > "$OUT"

echo "staged:"
echo "  app/www/ui        $(ls app/www/ui | wc -l | tr -d ' ') files"
echo "  app/www/sim       $(ls app/www/sim | wc -l | tr -d ' ') files"
echo "  app/www/cards     $(ls app/www/cards | wc -l | tr -d ' ') files"
echo "  $OUT  ($(wc -l < "$OUT" | tr -d ' ') lines, $(wc -c < "$OUT" | tr -d ' ') bytes)"
