# ClockClock 24 - board B: wall column 1, mini-clocks 1 / 3 / 5.
# A listener. Everything else lives in common_slave.yaml.

packages:
  slave: !include common_slave.yaml

substitutions:
#  clock_index_a: "1"
#  clock_index_b: "3"
#  clock_index_c: "5"
  clock_index_a: "19"
  clock_index_b: "21"
  clock_index_c: "23"
